My Project: Date.h File Reference
Date.h File Reference
used to create date object
#include <iostream>
Classes
class Date
Represents a date with day, month, and year information.
Functions
ostream & operator<< (ostream &os, const Date &date)
Overloaded insertion operator for output.
istream & operator>> (istream &is, Date &date)
Overloaded extraction operator for input.
Detailed Description
used to create date object
Author
Khon Min Thite
Version
0.1
Date
18-2-2024
Definition in file Date.h.
Function Documentation
operator<<()
ostream & operator<< (ostream & os, const Date & date)
Overloaded insertion operator for output.
Parameters
os The output stream.
date The Date object to output.
Returns
The output stream.
Definition at line 69 of file Date.cpp.
{
    os << " Date   : "  << date.GetDay() << " " << date.GetMonth() << " " << date.GetYear();
    return os;
}
operator>>()
istream & operator>> (istream & is, Date & date)
Overloaded extraction operator for input.
Parameters
is The input stream.
date The Date object to input into.
Returns
The input stream.
Definition at line 53 of file Date.cpp.
{
    int day, month, year;
    char delimiter;
    if (input >> day >> delimiter >> month >> delimiter >> year)
    {
        date.SetDay(day);
        date.SetMonth(month);
        date.SetYear(year);
    }
    return input;
}
References Date::SetDay(), Date::SetMonth(), and Date::SetYear().