My Project: Logic Class Reference
Logic Class Reference
#include <Logic.h>
Public Member Functions
void LoadDataFileCSV (ifstream &inputFile, Vector< Weather > &WindLog)
Load the data of an input data file and store it in a Vector.
void DisplayMenu ()
Displays the menu.
string RemoveLeadingZeros (string input)
Removes leading 0 from a given string.
float AverageWindSpeedMonth (const Vector< Weather > &array, const int month, const int year)
Search and Calculates the average wind speed of a month when given the month and year to search for.
float AverageAirTemperatureMonth (const Vector< Weather > &array, const int month, const int year)
Search and Calculates the average air temperature of a month when given the month and year to search for.
float SumSolarRadiationMonth (const Vector< Weather > &array, const int month, const int year)
Search and Calculates the total solar radiation of a month when given the month and year to search for.
string IntMonthToString (const int &month)
Converts a given integer month to string month.
float ConvertWindMStoKMH (const float &windSpeed)
Converts wind speed m/s to km/h.
float ConvertSolarRadiationWMtoKWH (const float &radiation)
Converts solar radiation from W per 10 min to KiloWattHour.
float StandardDeviationWindSpeedMonth (const Vector< Weather > &array, const int month, const int year)
Search and Calculates the standard deviation for wind speed of a month when given the month and year to search for.
float StandardDeviationAirTemperatureMonth (const Vector< Weather > &array, const int month, const int year)
Search and Calculates the standard deviation for ambient air temperature of a month when given the month and year to search for.
void WriteAppendFile (const string &output)
Create/Appends a given string into "WindTempSolar.csv".
Detailed Description
Definition at line 29 of file Logic.h.
Member Function Documentation
AverageAirTemperatureMonth()
float Logic::AverageAirTemperatureMonth (const Vector< Weather > & array, const int month, const int year)
Search and Calculates the average air temperature of a month when given the month and year to search for.
Parameters
array - The Vector to search in
month - The month to search for
year - The year to search for
Returns
float - The average air temperature of a month
Definition at line 210 of file Logic.cpp.
{
    float totalAirTemperature = 0.0;
    int count = 0;
    //Loops through each record in file, search for match month and year and add to totalAirTemperature
    //The number of matching records are kept track of
    for (unsigned int i = 0; i < array.Size(); i++)
    {
        if (array[i].GetDate().GetMonth() == month && array[i].GetDate().GetYear() == year)
        {
            count++;
            totalAirTemperature += array[i].GetAirTemperature();
        }
    }
    //If no record with matching month and year is found then return -1 else return calculated average airTemperature
    if (count == 0)
    {
        return -1;
    }
    else
    {
        return totalAirTemperature / count;
    }
}
AverageWindSpeedMonth()
float Logic::AverageWindSpeedMonth (const Vector< Weather > & array, const int month, const int year)
Search and Calculates the average wind speed of a month when given the month and year to search for.
Parameters
array - The Vector to search in
month - The month to search for
year - The year to search for
Returns
float - The average wind speed of a month
Definition at line 184 of file Logic.cpp.
{
    float totalWindSpeed = 0.0;
    int count = 0;
    //For each record in file, search for matching month and year and add to total wind speed
    //The number of matches are counted
    for (unsigned int i = 0; i < array.Size(); i++)
    {
        if (array[i].GetDate().GetMonth() == month && array[i].GetDate().GetYear() == year)
        {
            count++;
            totalWindSpeed += array[i].GetWindSpeed();
        }
    }
    //If no record with matching month and year is found then return -1 else return calculated average wind speed
    if (count == 0)
    {
        return -1;
    }
    else
    {
        return totalWindSpeed / count;
    }
}
ConvertSolarRadiationWMtoKWH()
float Logic::ConvertSolarRadiationWMtoKWH (const float & radiation)
Converts solar radiation from W per 10 min to KiloWattHour.
Parameters
radiation - Radiation in W per 10 min
Returns
float - Radiation in KiloWattHour
Definition at line 389 of file Logic.cpp.
{
    if (radiation > 0)
    {
        return (radiation/6) /  1000;
    }
    return 0;
}
Referenced by main().
ConvertWindMStoKMH()
float Logic::ConvertWindMStoKMH (const float & windSpeed)
Converts wind speed m/s to km/h.
Parameters
windSpeed - wind speed in m/s
Returns
float - wind speed in km/h
Definition at line 384 of file Logic.cpp.
{
    return windSpeed * 3.6;
}
Referenced by main().
DisplayMenu()
void Logic::DisplayMenu ()
Displays the menu.
Definition at line 170 of file Logic.cpp.
{
    cout << "1. Average wind speed in km/h and standard deviation for a given specified month and year." << endl;
    cout << "2. Average ambient air temperature and sample standard deviation for each month of a specified year." << endl;
    cout << "3. Total solar radiation in kWh/m2 for each month of a specified year." << endl;
    cout << "4. Average wind speed in km/h(standard deviation), average ambient air temperature(standard deviation) and total solar radiation in kWh/m2 for each month of a specified year." << endl;
    cout << "5. Exit the program." << endl;
}
Referenced by main().
IntMonthToString()
string Logic::IntMonthToString (const int & month)
Converts a given integer month to string month.
Parameters
month - A month in integer
Returns
string - A month in string
Definition at line 350 of file Logic.cpp.
{
    switch (month)
    {
    case 1:
        return "January";
    case 2:
        return "February";
    case 3:
        return "March";
    case 4:
        return "April";
    case 5:
        return "May";
    case 6:
        return "June";
    case 7:
        return "July";
    case 8:
        return "August";
    case 9:
        return "September";
    case 10:
        return "October";
    case 11:
        return "November";
    case 12:
        return "December";
    default:
        cout << endl << "Error converting int month to string" << endl;
        return "ERROR";
    }
}
LoadDataFileCSV()
void Logic::LoadDataFileCSV (ifstream & inputFile, Vector< Weather > & WindLog)
Load the data of an input data file and store it in a Vector.
Parameters
inputFile - The input file
WindLog - The Vector
Definition at line 13 of file Logic.cpp.
{
    // Keeps track of the number of elements split from a given string
    unsigned int recordCount = 0, rowFieldCount = 0, datetimeCount = 0, dateCount = 0, timeCount = 0;
    // A temp storage for split string
    string line, rowField, datetimeField, dateField, timeField;
    // A temp storage for split string
    Vector<string> columns, splitDateTime, splitDate, splitTime;
    // Temp storage for Date object
    Date tempDate;
    // Temp storage for Time object
    Time tempTime;
    // Initializes ValidationHelper
    Validator Validate;
    // Temp storage for Weather object
    Weather tempLog;
    // input string stream for reading and splitting of elements
    istringstream row, datetime, date, time;
    // Get and ignore CSV header
    getline(inputFile, line);
    string columnNames[] = {"WAST", "S", "SR", "T"};
    int columnIndices[4] = {-1, -1, -1, -1};
    istringstream headerStream(line);
    string columnName;
    int columnIndex = 0;
    while (getline(headerStream, columnName, ','))
    {
        for (int i = 0; i < 4; i++)
        {
            if (columnName == columnNames[i])
            {
                columnIndices[i] = columnIndex;
                break;
            }
        }
        columnIndex++;
    }
    while (getline(inputFile, line))
    {
        if (line != "")
        {
            row.str(line);
            while (getline(row, rowField, ','))
            {
                columns.Insert(rowFieldCount, rowField);
                rowFieldCount++;
            }
            row.clear();
            // Skip record if "WAST" column is empty
            if (columnIndices[0] != -1 && columns[columnIndices[0]] == "")
            {
                cout << "Warning: Empty 'WAST' field detected at row " << recordCount + 1 << endl;
                continue; // Skip to the next record
            }
            // Assuming "WAST" column is always present, but its fields can be empty
            datetime.str(columns[columnIndices[0]]);
            while (getline(datetime, datetimeField, ' '))
            {
                splitDateTime.Insert(datetimeCount, datetimeField);
                datetimeCount++;
            }
            datetime.clear();
            // Handle empty date/time fields
            if (splitDateTime.Size() > 0)
            {
                date.str(splitDateTime[0]);
                while (getline(date, dateField, '/'))
                {
                    splitDate.Insert(dateCount, RemoveLeadingZeros(dateField));
                    dateCount++;
                }
                date.clear();
                if (splitDate.Size() == 3 && Validate.IsValidDate(stoi(splitDate[0]), stoi(splitDate[1]), stoi(splitDate[2])))
                {
                    tempDate.SetDay(stoi(splitDate[0]));
                    tempDate.SetMonth(stoi(splitDate[1]));
                    tempDate.SetYear(stoi(splitDate[2]));
                }
                else
                {
                    cout << "Warning: Invalid date(WAST) detected at row " << recordCount + 1 << endl;
                }
                if (splitDateTime.Size() > 1)
                {
                    time.str(splitDateTime[1]);
                    while (getline(time, timeField, ':'))
                    {
                        splitTime.Insert(timeCount, RemoveLeadingZeros(timeField));
                        timeCount++;
                    }
                    time.clear();
                    if (splitTime.Size() == 2 && Validate.IsValid24HourTime(stoi(splitTime[0]), stoi(splitTime[1])))
                    {
                        tempTime.SetHour(stoi(splitTime[0]));
                        tempTime.SetMinute(stoi(splitTime[1]));
                    }
                    else
                    {
                        cout << "Warning: Invalid time(WAST) detected at row: " << recordCount + 1 << endl;
                    }
                }
            }
            // Validate and set other fields only if they are not empty
            for (int i = 1; i < 4; i++) // Start from 1 to skip "WAST"
            {
                if (columnIndices[i] != -1 && columns[columnIndices[i]] != "" && Validate.IsNumber(columns[columnIndices[i]]))
                {
                    switch (i)
                    {
                        case 1: tempLog.SetWindSpeed(stof(columns[columnIndices[i]])); break;
                        case 2: tempLog.SetSolarRadiation(stof(columns[columnIndices[i]])); break;
                        case 3: tempLog.SetAirTemp(stof(columns[columnIndices[i]])); break;
                    }
                }
                else if (columns[columnIndices[i]] != "") // Only print warning if the field is not empty
                {
                    cout << "Warning: Invalid data detected for " << columnNames[i] << " at row: " << recordCount + 1 << endl;
                }
            }
            // Insert tempLog into Vector WindLog only if all necessary fields are valid
            if (datetimeCount > 0) // Assuming at least date is present
            {
                tempLog.SetDate(tempDate);
                tempLog.SetTime(tempTime);
                WindLog.Insert(recordCount, tempLog);
            }
            // Clear the temp storage vectors
            columns.Clear();
            splitDateTime.Clear();
            splitDate.Clear();
            splitTime.Clear();
            // Reset count
            rowFieldCount = 0;
            datetimeCount = 0;
            dateCount = 0;
            timeCount = 0;
            recordCount++;
        }
    }
}
RemoveLeadingZeros()
string Logic::RemoveLeadingZeros (string input)
Removes leading 0 from a given string.
Parameters
input - The input string
Returns
string - The string after removing leading 0
Definition at line 179 of file Logic.cpp.
{
    return input.erase(0, min(input.find_first_not_of('0'), input.size() - 1));
}
StandardDeviationAirTemperatureMonth()
float Logic::StandardDeviationAirTemperatureMonth (const Vector< Weather > & array, const int month, const int year)
Search and Calculates the standard deviation for ambient air temperature of a month when given the month and year to search for.
Parameters
array - The Vector to search in
month - The month to search for
year - The year to search for
Returns
float - The standard deviation for air temperature of a month
Definition at line 306 of file Logic.cpp.
{
    Vector<float> airTemperatures;
    int count =  0;
    // Loop through the Vector to find all entries for the specified month and year
    for (unsigned int i =  0; i < array.Size(); i++)
    {
        if (array[i].GetDate().GetMonth() == month && array[i].GetDate().GetYear() == year)
        {
            count++;
            airTemperatures.Insert(count -  1, array[i].GetAirTemperature()); // Assuming GetAirTemp() returns the air temperature
        }
    }
    // If no data for the specified month and year, return -1
    if (count ==  0)
    {
        return -1; // No data for the specified month and year
    }
    float sum =  0.0;
    // Calculate the sum of all air temperatures
    for (unsigned int i =  0; i < airTemperatures.Size(); i++)
    {
        sum += airTemperatures[i];
    }
    float mean = sum / count; // Calculate the mean air temperature
    float sq_sum =  0.0;
    // Calculate the sum of the squared differences from the mean
    for (unsigned int i =  0; i < airTemperatures.Size(); i++)
    {
        float diff = airTemperatures[i] - mean;
        sq_sum += diff * diff;
    }
    float variance = sq_sum / (count -  1); // Calculate the variance
    // Calculate the standard deviation from the variance
    float stdev = sqrt(variance);
    return round(stdev * 100) /100;
}
StandardDeviationWindSpeedMonth()
float Logic::StandardDeviationWindSpeedMonth (const Vector< Weather > & array, const int month, const int year)
Search and Calculates the standard deviation for wind speed of a month when given the month and year to search for.
Parameters
array - The Vector to search in
month - The month to search for
year - The year to search for
Returns
float - The standard deviation for wind speed of a month
Definition at line 267 of file Logic.cpp.
{
    Vector<float> windSpeeds;
    int count =  0;
    for (unsigned int i =  0; i < array.Size(); i++)
    {
        if (array[i].GetDate().GetMonth() == month && array[i].GetDate().GetYear() == year)
        {
            count++;
            windSpeeds.Insert(count -  1, array[i].GetWindSpeed());
        }
    }
    if (count ==  0)
    {
        return -1; // No data for the specified month and year
    }
    float sum =  0.0;
    for (unsigned int i =  0; i < windSpeeds.Size(); i++)
    {
        sum += windSpeeds[i];
    }
    float mean = sum / count;
    float sq_sum =  0.0;
    for (unsigned int i =  0; i < windSpeeds.Size(); i++)
    {
        float diff = windSpeeds[i] - mean;
        sq_sum += diff * diff;
    }
    float variance = sq_sum / (count -  1);
    float stdev = sqrt(variance);
    return round(stdev *  100) /  100;
}
SumSolarRadiationMonth()
float Logic::SumSolarRadiationMonth (const Vector< Weather > & array, const int month, const int year)
Search and Calculates the total solar radiation of a month when given the month and year to search for.
Parameters
array - The Vector to search in
month - The month to search for
year - The year to search for
Returns
float - The total solar radiation of a month
Definition at line 237 of file Logic.cpp.
{
    float totalSolarRadiation = 0.0;
    int count = 0;
    //Loops through each record in file, search for matching month and year and add to total solar Radiation
    //The number of matching records are kept track of
    for (unsigned int i = 0; i < array.Size(); i++)
    {
        if (array[i].GetDate().GetMonth() == month && array[i].GetDate().GetYear() == year)
        {
            count++;
            if (array[i].GetSolarRadiation() > 100)
            {
                totalSolarRadiation += array[i].GetSolarRadiation();
            }
        }
    }
    //If no records with matching month and year is found then return -1 else return the totalSolarRadiation
    if (count > 0)
    {
        return totalSolarRadiation;
    }
    else
    {
        return -1;
    }
}
WriteAppendFile()
void Logic::WriteAppendFile (const string & output)
Create/Appends a given string into "WindTempSolar.csv".
Parameters
output - The string to append
Definition at line 398 of file Logic.cpp.
{
    ofstream OutputFile("WindTempSolar.csv", ofstream::app);
    //appends the string and proceed to next line
    OutputFile << output << endl;
    OutputFile.close();
}
The documentation for this class was generated from the following files:
Logic.h
Logic.cpp